apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: databox
  name: databox
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"databox:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"databox\")].image"}]'
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: databox
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        app.kubernetes.io/component: databox
    spec:
      containers:
        - image: databox:latest
          imagePullPolicy: Always
          name: databox
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 0
              memory: 0
