apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: databox
spec:
  tags:
  - from:
      kind: DockerImage
      name: ghcr.io/b4mad/racing-databox:latest
    importPolicy:
      scheduled: true
    name: latest
    referencePolicy:
      type: Source
