apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: databox
  name: databox
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/component: databox
