apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: pitwall
  title: Pitwall
  description: The Pitwall visualizes all incoming telemetry in real time - based on Grafana
  links:
    - url: https://pitwall.b4mad.racing/
      title: Pitwall
      icon: web
spec:
  owner: group:racing
