apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: postgraphile
  description: GraphQL API for PostgreSQL data
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=postgraphile'
  tags:
    - graphql
    - api
spec:
  type: service
  lifecycle: production
  owner: group:racing
  system: data-processing
  consumesApis:
    - postgresql-api
  providesApis:
    - graphql-api
