apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: telegraf
  description: Data collection and processing agent
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/component=telegraf'
  tags:
    - processing
    - metrics
spec:
  type: service
  lifecycle: production
  owner: group:racing
  system: data-processing
  consumesApis:
    - influxdb-api
