apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: b4mad-racing

resources:
  - ../../../base/databox/
  - ingress.yaml

images:
  - name: databox
    newName: image-registry.openshift-image-registry.svc:5000/b4mad-racing/databox
    newTag: latest
