apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: paddock-website
  description: Paddock web interface for race data management
  annotations:
    backstage.io/kubernetes-id: paddock-website
    backstage.io/kubernetes-namespace: b4mad-racing
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/component=paddock-website'
  tags:
    - django
    - web
spec:
  type: website
  lifecycle: production
  owner: group:racing
  system: paddock
  dependsOn:
    - resource:postgresql
    - resource:paddock-media-storage
