apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: systems
  description: "A collection of all #B4mad Racing systems"
spec:
  targets:
    - ./systems/pitwall.yaml
    - ./systems/paddock.yaml
