apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  instances: 1
  imageName: ghcr.io/imusmanmalik/timescaledb-postgis:14
  bootstrap:
    initdb:
      database: paddock
      owner: paddock
      postInitTemplateSQL:
        - CREATE EXTENSION timescaledb;
        - CREATE EXTENSION postgis;
        - CREATE EXTENSION postgis_topology;
        - CREATE EXTENSION fuzzystrmatch;
        - CREATE EXTENSION postgis_tiger_geocoder;
        - CREATE USER reader WITH PASSWORD 'paddock';
        - GRANT CONNECT ON DATABASE paddock TO reader;
        - GRANT USAGE ON SCHEMA public TO reader;
        - GRANT SELECT ON telemetry_game TO reader;
        - GRANT SELECT ON telemetry_car TO reader;
  enableSuperuserAccess: True
  postgresql:
    shared_preload_libraries:
      - timescaledb
  storage:
    size: 1Gi
