apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: paddock-website
  name: paddock
spec:
  ports:
    - name: django-web
      port: 8000
      targetPort: django-http
  selector:
    app.kubernetes.io/component: paddock-website
