apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgraphile
  labels:
    app: postgraphile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgraphile
  template:
    metadata:
      labels:
        app: postgraphile
    spec:
      containers:
      - name: postgraphile
        image: graphile/postgraphile:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgres://user:password@hostname:5432/dbname"
        - name: SCHEMA
          value: "public"
