apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgraphile
  labels:
    app: postgraphile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgraphile
  template:
    metadata:
      labels:
        app: postgraphile
    spec:
      containers:
      - name: postgraphile
        image: graphile/postgraphile:next
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_URL
            value: "postgresql://reader:paddock@postgresql-r:5432/paddock"
          - name: SCHEMA
            value: "public"
        args:
        - --no-ignore-rbac
        - --enhance-graphiql
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
