apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: paddock
  title: Paddock
  description: A django application providing the website and copilots
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/b4mad/racing/tree/main/components/paddock
    backstage.io/kubernetes-id: b4mad-racing
    backstage.io/kubernetes-namespace: b4mad-racing
    github.com/project-slug: b4mad/racing
  links:
    - url: https://b4mad.racing/
      title: Paddock
      icon: web
spec:
  owner: group:racing
  system: paddock
