apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pg-cluster
  title: PostgreSQL cluster
  description: PostgreSQL is a powerful, open source object-relational database system. PostgreSQL cluster is created by Crunchy Postgres for Kubernetes operator
  annotations:
    backstage.io/kubernetes-label-selector: "postgres-operator.crunchydata.com/cluster=db"
    backstage.io/kubernetes-namespace: b4mad-racing
    backstage.io/kubernetes-id: b4mad-racing
    github.com/project-slug: b4mad/racing
spec:
  type: service
  lifecycle: production
  owner: group:racing
  system: paddock
  dependsOn:
    - component:cloud-native-pg-operator
    - resource:cluster-phobos
